INSERT INTO `filmy` (`ID_FILM`, `NAZWA`, `GATUNEK`) VALUES
(1,'OGNIEM I MIECZEM', 'HISTORYCZNY'),
(2,'WLADCA PIERŚCIENI' , 'FANTASY'), (30, 'SYSTEMY EKSPERCKIE', 'STRZELECKA 14'),
(3,'HARRY POTTER I KOMNATA TAJEMNIC', 'DLA MŁODZIEŻY'),
(4,'OXYGEN', 'HORROR');